require('dotenv').config()
const express = require("express")
const cors = require("cors")
const corsOptions = require("./config/corsOptions")
const PORT =process.env.PORT||1234
const mongoose= require("mongoose")
const app = express()
const DBconnect=require("./config/connectDB.js")
DBconnect()
app.use(cors(corsOptions))
app.use(express.json())
app.use(express.static("public"))
app.get("/",(req,res)=>{res.send("this is the home page")})
app.use("/donor",require("./routes/donors"))
app.use("/donation",require("./routes/donations"))
app.use("/event",require("./routes/events"))
app.use("/auth",require("./routes/auth"))
app.use("/creditDetails",require("./routes/creditDetails"))
app.use("/category",require("./routes/category"))
app.use("/supported", require("./routes/supported"));
mongoose.connection.once('open',()=>{app.listen(PORT,()=>{console.log(`the port is ${PORT}`)})})
mongoose.connection.on('error',err=>{})
