require('dotenv').config()
const express = require("express")
const cors = require("cors")
const corsOptions = require("./config/corsOptions")
const PORT =process.env.PORT||1234
const mongoose= require("mongoose")
const app = express()
const DBconnect=require("./config/connectDB.js")
DBconnect()
app.use(cors(corsOptions))
app.use(express.json())
app.use(express.static("public"))
app.use("/api/donor",require("./routes/donors"))
app.use("/api/donation",require("./routes/donations"))
app.use("/api/auth",require("./routes/auth"))
app.use("/api/creditDetails",require("./routes/creditDetails"))
app.use("/api/category",require("./routes/category"))
app.use("/api/supported", require("./routes/supported"));
mongoose.connection.once('open',()=>{app.listen(PORT,()=>{console.log(`the port is ${PORT}`)})})
mongoose.connection.on('error',err=>{})
